version: '3.8'

services:
  questions_db:
    image: postgres:15
    container_name: questions_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: questions_pass
      POSTGRES_DB: questions_db
    ports:
      - "5433:5432"
    volumes:
      - questions_data:/var/lib/postgresql/data

  answers_db:
    image: postgres:15
    container_name: answers_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: answers_pass
      POSTGRES_DB: answers_db
    ports:
      - "5434:5432"
    volumes:
      - answers_data:/var/lib/postgresql/data

  quiz_app:
    build:
      context: .
    container_name: quiz_app
    depends_on:
      - questions_db
      - answers_db
    environment:
      QUESTIONS_DB_HOST: questions_db
      QUESTIONS_DB_PORT: 5432
      ANSWERS_DB_HOST: answers_db
      ANSWERS_DB_PORT: 5432
    command: python quiz_game.py

volumes:
  questions_data:
  answers_data:
